
const quotes = [
    // Marcus Aurelius    
    "You have power over your mind—not outside events. Realize this, and you will find strength.",
    "Dwell on the beauty of life. Watch the stars, and see yourself running with them.",
    "The happiness of your life depends upon the quality of your thoughts.",
    "Waste no more time arguing what a good man should be. Be one.",
    "It is not death that a man should fear, but he should fear never beginning to live.",
    "When you arise in the morning, think of what a privilege it is to be alive, to think, to enjoy, to love.",
    "You are what you repeatedly do. Excellence, then, is not an act, but a habit.",
    "If it is not right, do not do it; if it is not true, do not say it.",
    "Confine yourself to the present.",
    "The best revenge is not to be like your enemy.",
    // Seneca
    "Begin at once to live, and count each separate day as a separate life.",
    "Luck is what happens when preparation meets opportunity.",
    "It is not the man who has too little, but the man who craves more, that is poor.",
    "We suffer more often in imagination than in reality.",
    "He who is brave is free.",
    "Difficulty strengthens the mind, as labor does the body.",
    "As is a tale, so is life: Not how long it is, but how good it is, is what matters.",
    "Hang on to your youthful enthusiasms—you'll be able to use them better when you're older.",
    "Throw me to the wolves and I will return leading the pack.",
    "Only time can heal what reason cannot.",
    // Epictus
    "Man is not worried by real problems so much as by his imagined anxieties about real problems.",
    "Wealth consists not in having great possessions, but in having few wants.",
    "Don’t explain your philosophy. Embody it.",
    "First say to yourself what you would be; and then do what you have to do.",
    "It’s not what happens to you, but how you react to it that matters.",
    "No man is free who is not master of himself.",
    "Circumstances don’t make the man, they only reveal him to himself.",
    "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.",
    "The key is to keep company only with people who uplift you, whose presence calls forth your best.",
    "He who laughs at himself never runs out of things to laugh at.",
    // Zeno of Citium
    "Happiness is a good flow of life.",
    "Well-being is realized by small steps, but is truly no small thing.",
    "Man conquers the world by conquering himself.",
    "The goal of life is living in agreement with nature.",
    "Fate is the endless chain of causation, whereby things are; the reason or formula by which the world goes on.",
    // Musonius Rufus
    "If you accomplish something good with hard work, the labor passes quickly, but the good endures.",
    "To bear trials with a calm mind robs misfortune of its strength and burden.",
    "No evil is honorable; but death is honorable. Therefore death is not evil.",
    "Practicing virtue is a kind of work.",
    "The person who has practiced philosophy as a cure for the self becomes an example to others.",
    // Miscellaneous stoic wisdom
    "Control your emotions or they will control you.",
    "Courage is the resistance to fear, mastery of fear—not the absence of fear.",
    "The obstacle is the way.",
    "Be tolerant with others and strict with yourself.",
    "Do not seek for things to happen the way you want them to; rather, wish that what happens happen the way it happens, and you will be happy.",
    "Adversity introduces a man to himself.",
    "Do every act of your life as if it were your last.",
    "What we do now echoes in eternity.",
    "While we wait for life, life passes.",
    "Every night, before going to sleep, we must ask ourselves: What weakness did I overcome today? What virtue did I acquire?",
    "A gem cannot be polished without friction, nor a man perfected without trials.",
    "Time is like a river. You cannot touch the same water twice.",
    "Do not be ashamed of help.",
    "If you wish to improve, be content to appear clueless or stupid.",
    "True happiness is to enjoy the present without anxious dependence on the future.",
    "He suffers more than necessary, who suffers before it is necessary.",
    "No great thing is created suddenly.",
    "The greater the difficulty, the more glory in surmounting it.",
    "To live a good life: We have the potential for it. If we learn to be indifferent to what makes no difference.",
    "A wise man is content with his lot, whatever it may be.",
    "You always own the option of having no opinion.",
    "What is hard to bear is sweet to remember.",
    "Self-control is strength. Right thought is mastery. Calmness is power.",
    "Nothing endures but change.",
    "Be like a rock that the waves keep crashing over. It stands unmoved, and the raging of the sea falls still around it.",
    "Keep silence for the most part, and speak only when you must.",
    "To be stoic is not to be emotionless, but to remain unaffected by your emotions.",
    "Virtue alone is sufficient for happiness.",
    "Everything that happens, happens as it should.",
    "Be mindful, not mind-full.",
    "What you throw on the fire, the fire consumes.",
    "Do not be afraid of death, but be afraid of never beginning to live.",
    "The wise man is neither raised up by prosperity nor cast down by adversity.",
    "Contentment comes from wanting less, not having more.",
    "You can commit injustice by doing nothing.",
    "Let philosophy scrape off your own faults, rather than be a way to rail against the faults of others.",
    "Our life is what our thoughts make it.",
    "Set aside a certain number of days where you will live only on the basics.",
    "What stands in the way becomes the way.",
    "Do not anticipate trouble, or worry about what may never happen.",
    "He who has a why to live can bear almost any how.",
    "Never let the future disturb you.",
    "Don’t be overheard complaining about life at court. Not even to yourself.",
    "Be content with what you are, and wish not change.",
    "Reason and judgment are the masters of all human action.",
    "Don’t seek to be relevant. Just seek to be excellent.",
    "Nature gave us one tongue and two ears so we could listen twice as much as we speak.",
    "If you are pained by an external thing, it is not the thing that disturbs you, but your own judgment about it.",
    "Don’t return injury for injury.",
    "Receive without pride, let go without attachment.",
    "To die is nothing terrible; but to die as we’ve lived—out of tune with ourselves, ungrateful, grieved, discontented—this is the problem.",
    "Who then is invincible? The one who cannot be upset by anything outside their reasoned choice.",
    "Do not be concerned with other people’s impressions of you.",
    "What we fear doing most is usually what we most need to do.",
    "Stop letting yourself be pulled in all directions.",
    "Make the mind tougher by exposing it to adversity.",
    "You could leave life right now. Let that determine what you do and say and think.",
    "A setback is an opportunity for a comeback.",
    "Look back over the past, with its changing empires that rose and fell, and you can foresee the future too.",
    "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth."
];

const randomQuote = quotes => {
    var index = Math.floor(Math.random() * quotes.length);
    console.log(index);
    console.log("Your quote of the day is:");
    console.log(quotes[index]);
};

randomQuote(quotes);